import Script from "next/script";
import "./globals.css";
import { Grommet } from "grommet";
import { hpe } from "grommet-theme-hpe";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <Script src="https://h50007.www5.hpe.com/hfws-static/js/framework/jquery/v-3-6-0/jquery.js" />
        <Script src="https://h50007.www5.hpe.com/hfws/us/en/hpe/latest.r/root?contentType=js&switchToCHF=true&hide_cart=true&hide_sign_in=true&slim_footer=true&hide_sitemap=true&expand_view=false" />
      </head>
      <body className={`antialiased`}>
        <div id="header" className="header"></div>
        <Grommet className="App" theme={hpe}>
          {children}
        </Grommet>

        <div id="footer" className="footer"></div>
      </body>
    </html>
  );
}
